### ISSUE TITLE
Police Mercedes shoult be Sgt+

### ISSUE THREAD

**Issue by TinySimon** [FredyH/Perpheads-Issues#561]
The RTU Mercedes should only be spawnable by a sergeant or higher

**Comment by Exnem** [comment]
I completely agree with this, since day 1 it was available for corporals. I don't believe senior officers have access to it however.
Nevertheless, it makes the little sentence in the vehicle policy obsolete if you're going to be fixing this.

As such: 2.5 The Mercedes SL65 AMG may only be driven by an Officer ranked Sergeant or higher. The exception to this is life threatening situations.

Implying that the mercedes may be driven by corporals, in said circumstance, such as high speed pursuits and no SGT is available. Etc.

**Comment by Exnem** [comment]
Nevermind what I said about senior officers, they can also bring out the SLS.

**Comment by FredyH** [comment]
fixed
