### ISSUE TITLE
Gun mag glitch?

### ISSUE THREAD

**Issue by A1LARSEN** [FredyH/Perpheads-Issues#661]
I was growing and I was messing around with my gun taking it out maybe when it was about to load then it legit like, doesn't show that there is a mag in there or nothing, but allows me to actually still shoot the gun, wasting no ammo or mag in the progress. Will provide video proof after, just will report this issue/bug though

**Comment by LaCreepis** [comment]
Had this happen to me as TFU when I tried reloading my gun as TFU it just wouldn't let me and putting it away just resulted in it having a empty mag but still being able to shoot it. Might be having to do with the amount of mags you have on you, 15 is max and I had G3A3 mags on me because of that silly taser glitch and it wouldn't allow me to reload.

**Comment by TinySimon** [comment]
Hopefully fixed now
