### ISSUE TITLE
Burst fire mode is broken

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#743]
Title, firing a gun with burst fire will greet you with a nice 'burst' of high recoil when spam firing it which is higher than usual, making it harder to control. Been broken since the day of the new weapon models.

**Comment by TinySimon** [comment]
I'm not sure exactly what you want changed.

If you spam fire burst mode, it has almost exactly the same recoil impact as firing on full auto, which is to be expected. If you give yourself delays in the firing, you have a chance to adjust for this.

Most other games account for this by enforcing a delay between burst fires, rather than allowing them to be spammed. Would you want an enforced delay between burst fires, so that players are given a better opportunity to account for the recoil?

**Comment by LaCreepis** [comment]
@TinySimon can't see your reply in this #issue most likely because you deleted it but having a forced delay would also help with the issue. But again, the main issue I tried pointing out is that burst fire just has a lot of recoil involved for some reason, tap firing at the same speed in the semi-auto mode is more controllable and using burst. This was also brought up by 2 other people in a recent thread, I'm not the only one that noticed this https://i.imgur.com/auojmH7.png https://i.imgur.com/f0Plu69.png

**Comment by TinySimon** [comment]
I'm guessing the main issue is people are trying to fire burst mode at the same speed of full auto and are being surprised that the recoil is then the same as full auto.

Firing 3 bullets burst fire has approximately the same amount of recoil as firing 3 bullets in full auto, or 3 bullets fired at the same speed using semi-auto. However, it would be difficult to actually fire semi-auto at the speed that burst fire does. I'm happy to investigate this further if somebody can prove otherwise though.
